name: untitled
description: An absolute bare-bones web app.
# version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  image: ^2.0.4
  vector_math: ^2.0.8
  http: ^0.11.3+17
  tuple: ^1.0.2
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
